version: '3.7'

services:
  backend:
    container_name: landingpage
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - VIRTUAL_HOST=portfolio.anhnd.click
      - VIRTUAL_PORT=8090
      - LETSENCRYPT_HOST=portfolio.anhnd.click
      - LETSENCRYPT_EMAIL=anhnd350309@gmail.com

networks:
  default:
    name: nginx-proxy_default
